### ISSUE TITLE
change dependencies of package.json to support current angular

### ISSUE THREAD

**Issue by dohomi** [Urigo/angular2-meteor-auto-bootstrap#14]
Hi,
I would like to check out newest RC2 of angular and rxjs and reflect-metadata. Could you update the package.json? Thanks!

**Comment by barbatus** [comment]
Fixed in the recent commits.

**Comment by dohomi** [comment]
Hi @barbatus Thanks for this! Just out of curiosity, two packages are still not in their latest version possible to upgrade:

```
    "reflect-metadata": "0.1.2",
    "rxjs": "5.0.0-beta.6" 
```

**Comment by barbatus** [comment]
@dohomi this is dev dependencies, also Angular2 depends on the exact versions.

**Comment by dohomi** [comment]
@barbatus thanks for clarifying
