### ISSUE TITLE
Updated Versions: "Uncaught No provider for ApplicationRef"

### ISSUE THREAD

**Issue by ValentinFunk** [Urigo/angular2-meteor-auto-bootstrap#22]
When using the newest Versions (Meteor 1.4.1-rc.0 and Angular 2.0.0-rc.5) the following error occurs (using angular2-meteor-base):

![Issue](https://hostr.co/file/6LuR7hMjzMiR/Screenshoton2016-08-14at17.36.25.png)

Repo to reproduce: https://github.com/Kamshak/new-version-test

```
angular2-meteor-base@ C:\Dev\strong-ostrich\testrepo
+-- @angular/common@2.0.0-rc.5
+-- @angular/compiler@2.0.0-rc.5
+-- @angular/core@2.0.0-rc.5
+-- @angular/forms@0.3.0
+-- @angular/platform-browser@2.0.0-rc.5
+-- @angular/platform-browser-dynamic@2.0.0-rc.5
+-- @angular/router@3.0.0-rc.1
+-- angular2-meteor@0.6.2
+-- angular2-meteor-auto-bootstrap@0.6.0
+-- angular2-meteor-polyfills@0.1.1
+-- angular2-meteor-tests-polyfills@0.0.2
+-- bootstrap@4.0.0-alpha.3
| +-- jquery@3.1.0
| `-- tether@1.3.4
+-- chai@3.5.0
| +-- assertion-error@1.0.2
| +-- deep-eql@0.1.3
| | `-- type-detect@0.1.1
| `-- type-detect@1.0.0
+-- chai-spies@0.7.1
+-- es6-shim@0.35.1
+-- meteor-node-stubs@0.2.3
| +-- assert@1.3.0
| +-- browserify-zlib@0.1.4
| | `-- pako@0.2.8
| +-- buffer@4.5.1
| | +-- base64-js@1.1.2
| | +-- ieee754@1.1.6
| | `-- isarray@1.0.0
| +-- console-browserify@1.1.0
| | `-- date-now@0.1.4
| +-- constants-browserify@1.0.0
| +-- crypto-browserify@3.11.0
| | +-- browserify-cipher@1.0.0
| | | +-- browserify-aes@1.0.6
| | | | +-- buffer-xor@1.0.3
| | | | `-- cipher-base@1.0.2
| | | +-- browserify-des@1.0.0
| | | | +-- cipher-base@1.0.2
| | | | `-- des.js@1.0.0
| | | |   `-- minimalistic-assert@1.0.0
| | | `-- evp_bytestokey@1.0.0
| | +-- browserify-sign@4.0.0
| | | +-- bn.js@4.11.1
| | | +-- browserify-rsa@4.0.1
| | | +-- elliptic@6.2.3
| | | | +-- brorand@1.0.5
| | | | `-- hash.js@1.0.3
| | | `-- parse-asn1@5.0.0
| | |   +-- asn1.js@4.5.2
| | |   | `-- minimalistic-assert@1.0.0
| | |   +-- browserify-aes@1.0.6
| | |   | +-- buffer-xor@1.0.3
| | |   | `-- cipher-base@1.0.2
| | |   `-- evp_bytestokey@1.0.0
| | +-- create-ecdh@4.0.0
| | | +-- bn.js@4.11.1
| | | `-- elliptic@6.2.3
| | |   +-- brorand@1.0.5
| | |   `-- hash.js@1.0.3
| | +-- create-hash@1.1.2
| | | +-- cipher-base@1.0.2
| | | +-- ripemd160@1.0.1
| | | `-- sha.js@2.4.5
| | +-- create-hmac@1.1.4
| | +-- diffie-hellman@5.0.2
| | | +-- bn.js@4.11.1
| | | `-- miller-rabin@4.0.0
| | |   `-- brorand@1.0.5
| | +-- inherits@2.0.1
| | +-- pbkdf2@3.0.4
| | +-- public-encrypt@4.0.0
| | | +-- bn.js@4.11.1
| | | +-- browserify-rsa@4.0.1
| | | `-- parse-asn1@5.0.0
| | |   +-- asn1.js@4.5.2
| | |   | `-- minimalistic-assert@1.0.0
| | |   +-- browserify-aes@1.0.6
| | |   | +-- buffer-xor@1.0.3
| | |   | `-- cipher-base@1.0.2
| | |   `-- evp_bytestokey@1.0.0
| | `-- randombytes@2.0.3
| +-- domain-browser@1.1.7
| +-- events@1.1.0
| +-- http-browserify@1.7.0
| | +-- Base64@0.2.1
| | `-- inherits@2.0.1
| +-- https-browserify@0.0.1
| +-- os-browserify@0.2.1
| +-- path-browserify@0.0.0
| +-- process@0.11.2
| +-- punycode@1.4.1
| +-- querystring-es3@0.2.1
| +-- readable-stream@2.0.6
| | +-- core-util-is@1.0.2
| | +-- inherits@2.0.1
| | +-- isarray@1.0.0
| | +-- process-nextick-args@1.0.6
| | `-- util-deprecate@1.0.2
| +-- stream-browserify@2.0.1
| | `-- inherits@2.0.1
| +-- string_decoder@0.10.31
| +-- timers-browserify@1.4.2
| +-- tty-browserify@0.0.0
| +-- url@0.11.0
| | +-- punycode@1.3.2
| | `-- querystring@0.2.0
| +-- util@0.10.3
| | `-- inherits@2.0.1
| `-- vm-browserify@0.0.4
|   `-- indexof@0.0.1
+-- reflect-metadata@0.1.8
+-- rxjs@5.0.0-beta.6
`-- zone.js@0.6.12
```

**Comment by jbockerstette** [comment]
I have the exact same problem. In order to fix it, I had to back off to rc.4. Here is my dependencies I used to fix it. This is in your package.json.  After you update this file, run `meteor npm update`

```
 "dependencies": {
    "@angular/common": "2.0.0-rc.4",
    "@angular/compiler": "2.0.0-rc.4",
    "@angular/core": "2.0.0-rc.4",
    "@angular/platform-browser": "2.0.0-rc.4",
    "@angular/platform-browser-dynamic": "2.0.0-rc.4",
    "@angular/router": "3.0.0-beta.2",
    "@angular/router-deprecated": "2.0.0-rc.2",
    "@angular/upgrade": "2.0.0-rc.4",

```

**Comment by Feldor** [comment]
Thank for the solution, My problem has been resolved when I update the dependencies.
:)

**Comment by conglei** [comment]
@Feldor Could you share how you solve this problem by updating the dependencies?

**Comment by jbockerstette** [comment]
I didn't fix the problem. I had to roll back some of my dependencies in my
package.json. I pasted my dependencies in the issues page. After you update
those dependencies, then execute meteor npm update. That's all I did. Let
me know if I can help you more. Good luck.

**Comment by jbockerstette** [comment]
I didn't fix the problem. I had to roll back some of my dependencies in my
package.json. I pasted my dependencies in the issues page. After you update
those dependencies, then execute meteor npm update. That's all I did. Let
me know if I can help you more. Good luck.

On Aug 24, 2016 1:37 PM, "Conglei" notifications@github.com wrote:

@Feldor https://github.com/Feldor Could you share how you solve this
problem by updating the dependencies?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
https://github.com/Urigo/angular2-meteor-auto-bootstrap/issues/22#issuecomment-242199980,
or mute the thread

**Comment by barbatus** [comment]
obsolete
